# constants.sh
BOXCLI_ROOT_DIR="$1"
BOXCLI_INC_DIR="${BOXCLI_ROOT_DIR}/inc"
BOXCLI_LIB_DIR="${BOXCLI_ROOT_DIR}/lib"
BOXCLI_CMD_DIR="${BOXCLI_ROOT_DIR}/cmd"
BOXCLI_OPT_DIR="${BOXCLI_ROOT_DIR}/opt"
BOXCLI_TMP_DIR="/tmp/boxcli"

BOXCLI_IS_QUIET=""
BOXCLI_IS_JSON=""
BOXCLI_IS_COMPOSER=""

BOXCLI_CLAUSES=()
BOXCLI_OPTIONS=()
