# constants.sh
BOXCLI_ROOT_DIR="$1"
BOXCLI_INC_DIR="${BOXCLI_ROOT_DIR}/inc"
BOXCLI_LIB_DIR="${BOXCLI_ROOT_DIR}/lib"
BOXCLI_CMD_DIR="${BOXCLI_ROOT_DIR}/cmd"
BOXCLI_OPT_DIR="${BOXCLI_ROOT_DIR}/opt"

BOXCLI_CLAUSES=()
BOXCLI_OPTIONS=()
